name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npx hardhat compile
    - name: Start local node
      run: npx hardhat node
      background: true
    - name: Run tests
      run: npx hardhat test
    - name: Check code coverage
      run: npx hardhat coverage
      
networks:
  hardhat:
    chainId: 1337
    accounts:
      mnemonic: "test test test test test test test test test test test junk"
  localhost:
    url: "http://localhost:8545" 
