name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npx hardhat compile
    - name: Start local node
      run: npx hardhat node &
    - name: Wait for local node to start
      run: npx hardhat node --waitForUpgrade
    - name: Run tests
      run: npx hardhat test
    - name: Check code coverage
      run: npx hardhat coverage
      
